#!/usr/bin/env node
/**
 * MindGuard AI – Build Script
 *
 * Reads your .env file and generates config.js for the extension.
 * config.js is gitignored — the API key never touches source control.
 *
 * Usage:
 *   node build.js
 *
 * Requirements:
 *   Node.js 18+ (no npm install needed — uses only built-in modules)
 */

const fs   = require('fs');
const path = require('path');

// ── Read .env ────────────────────────────────────────────────────────────────
const envPath = path.join(__dirname, '.env');

if (!fs.existsSync(envPath)) {
  console.error('❌  .env file not found.');
  console.error('    Copy .env.example → .env and fill in your Gemini API key.');
  process.exit(1);
}

const env = {};
fs.readFileSync(envPath, 'utf8')
  .split('\n')
  .forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;
    const [key, ...rest] = line.split('=');
    env[key.trim()] = rest.join('=').trim();
  });

// ── Validate ─────────────────────────────────────────────────────────────────
const key = env.GEMINI_API_KEY || '';
if (!key || key === 'YOUR_GEMINI_API_KEY_HERE') {
  console.error('❌  GEMINI_API_KEY is not set in .env');
  console.error('    Get your free key at: https://aistudio.google.com/app/apikey');
  process.exit(1);
}

if (!key.startsWith('AIza')) {
  console.warn('⚠️   Key doesn\'t start with "AIza" — double-check it\'s a Gemini key.');
}

// ── Generate config.js ───────────────────────────────────────────────────────
const config = `/**
 * MindGuard AI – Auto-generated config
 * ⚠️  DO NOT EDIT THIS FILE DIRECTLY and do NOT commit it to git.
 *     Edit .env instead, then run: node build.js
 *
 * Generated: ${new Date().toISOString()}
 */

const MINDGUARD_CONFIG = {
  GEMINI_API_KEY:          '${key}',
  GEMINI_MODEL:            'gemini-2.5-flash',
  CONFIDENCE_THRESHOLD:     ${parseFloat(env.CONFIDENCE_THRESHOLD) || 0.65},
  DEBOUNCE_MS:              ${parseInt(env.DEBOUNCE_MS)            || 1200},
  COOLDOWN_MS:              ${parseInt(env.COOLDOWN_MS)            || 240000},
  MIN_CHARS:                ${parseInt(env.MIN_CHARS)              || 12},
};
`;

const outPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outPath, config, 'utf8');

console.log('✅  config.js generated successfully.');
console.log('    Key preview: ' + key.slice(0, 8) + '...' + key.slice(-4));
console.log('');
console.log('👉  Next step: load the extension folder into your browser.');
console.log('    Chrome/Brave: chrome://extensions → Load unpacked → select this folder');
