/**
 * MindGuard AI – Auto-generated config
 * ⚠️  DO NOT EDIT THIS FILE DIRECTLY and do NOT commit it to git.
 *     Edit .env instead, then run: node build.js
 *
 * Generated: 2026-03-13T16:26:43.141Z
 */

const MINDGUARD_CONFIG = {
  GEMINI_API_KEY:          'AI....',
  GEMINI_MODEL:            'gemini-2.5-flash',
  CONFIDENCE_THRESHOLD:     0.65,
  DEBOUNCE_MS:              1200,
  COOLDOWN_MS:              240000,
  MIN_CHARS:                12,
};
